"""Update FinishedGoods model

Revision ID: 29aff9ea24ef
Revises: 389e3a01717a
Create Date: 2024-10-12 08:04:44.255134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29aff9ea24ef'
down_revision: Union[str, None] = '389e3a01717a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
