"""Add not_in_wir_fg to finished_goods_inventory

Revision ID: 389e3a01717a
Revises: 58f9c79a4407
Create Date: 2024-10-11 14:25:06.741578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389e3a01717a'
down_revision: Union[str, None] = '58f9c79a4407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finished_goods_inventory', sa.Column('not_in_wir_fg', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finished_goods_inventory', 'not_in_wir_fg')
    # ### end Alembic commands ###
