"""Add new columns to FinishedGoodsInventory

Revision ID: 9e21944f5703
Revises: 4c84a87bc82a
Create Date: 2024-10-11 14:17:34.379951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e21944f5703'
down_revision: Union[str, None] = '4c84a87bc82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
